Allow use of std::optional in C++17
m-renaud/libdlibxx pull request #3
Opened 2017-12-22 13:58 UTC by bigdavedev

boost::optional is a fallback option if the feature detection fails

Signed-off-by: Dave Brown <d.brown@bigdavedev.com>

2017-12-22 14:53 UTC, m-renaud commented
Thanks for the PR!

Can you also update:
1. The "Dependencies" section in the readme to say either a. c++17 compiler or b. c++11 compiler and boost.optional
2. Create a CHANGELOG file in the repo root with a short description of the change
3. Drop the 11 from c++11 in the first paragraph of the readme

If possible (I should really set up a test suite) could you build and run the examples with c++11 and c++17 versions of gcc and clang?

2017-12-22 14:55 UTC, m-renaud requested changes

2017-12-22 14:55 UTC, m-renaud commented on include/dlibxx.hxx
> +	auto value = opt.value();
Can you inline the return here and in the BOOST_OPTIONAL case?

2017-12-22 16:59 UTC, m-renaud commented
Alternatively, I'm considering just bumping the major version to 2.0 and eliminating the boost dependency all together. I can update the docs to say if you only have a c++11 compiler then checkout tag 1.1.0 and use that.

2017-12-23 11:25 UTC, bigdavedev commented
One can use experimental/optional for C++14 using the same constructs in this pull request.

I can absolutely help with the readme. As for testing, I can include some tests for various compilers and c++ versions for this PR.

If you like, I can help with a general testsuite for the code base, since this is a library I am going to using :)

2017-12-23 17:50 UTC, m-renaud commented
> One can use experimental/optional for C++14

If you could add that too that would be great.

> As for testing, I can include some tests for various compilers and c++ versions for this PR.

Thanks, I wasn't sure if that was too much to ask since I didn't have anything in place already.

> I can help with a general testsuite for the code base

Absolutely appreciated! :) I've created https://github.com/m-renaud/libdlibxx/issues/4 to track that work, feel free to add comments and suggestions there.

2017-12-27 11:50 UTC, bigdavedev commented
Propose that this PR be put on hold until come CI is set up. This will allow the library in its current state to be tested and verified, allowing changes like this PR to be more easily scrutinized.

2018-01-19 09:12 UTC, closed without merging